[package]
name = "algorithms"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
rand = "0.9.0"
rayon = "1.10.0"
time_it_macro = {git = "https://github.com/LePhilippeDucTai/time_it_macro.git"}
